src/api/config/routes.rb
class WebuiMatcher
  class InvalidRequestFormat < APIError
  end

  def self.matches?(request)
    request.format.to_sym != :xml
  rescue ArgumentError => e
    raise InvalidRequestFormat, e.to_s
  end
end

# here we take everything that is XML, JSON or osc ;)
class APIMatcher
  def self.matches?(request)
    format = request.format.to_sym || :xml
    format == :xml || format == :json || public_or_about_path?(request)
  end

  def self.public_or_about_path?(request)
    request.fullpath.start_with?('/public', '/about')
  end
end

OBSApi::Application.routes.draw do
  mount Peek::Railtie => '/peek'

  cons = {
    arch: %r{[^\/]*},
    binary: %r{[^\/]*},
    filename: %r{[^\/]*},
    id: %r{\d*},
    login: %r{[^\/]*},
    package: %r{[^\/]*},
    package_name: %r{[^\/]*},
    project: %r{[^\/]*},
    project_name: %r{[^\/]*},
    maintained_project: %r{[^\/]*},
    repository: %r{[^\/]*},
    repository_name: %r{[^\/]*},
    service: %r{\w[^\/]*},
    title: %r{[^\/]*},
    user: %r{[^\/]*},
    user_login: %r{[^\/]*},
    repository_publish_build_id: %r{[^\/]*}
  }

  constraints(WebuiMatcher) do
    root 'webui/main#index'

    controller 'webui/main' do
      get 'main/systemstatus' => :systemstatus
    end

    resources :status_messages, only: [:create, :destroy], controller: 'webui/status_messages' do
      collection do
        get 'create_status_message_dialog' => :create_status_message_dialog
        get 'destroy_status_message_dialog' => :destroy_status_message_dialog
      end
    end

    controller 'webui/feeds' do
      get 'main/news' => :news, constraints: ->(req) { req.format == :rss }, as: :news_feed
      get 'main/latest_updates' => :latest_updates, constraints: ->(req) { req.format == :rss }, as: :latest_updates_feed
      get 'project/latest_commits/:project' => :commits, defaults: { format: 'atom' }, constraints: cons, as: 'commits_feed'
      get 'user/feed/:token' => :notifications, defaults: { format: 'rss' }, as: :user_rss_notifications
    end

    resources :attribs, constraints: cons, only: [:create, :update, :destroy], controller: 'webui/attribute' do
      collection do
        get ':project(/:package)/new' => :new, constraints: cons, as: 'new'
        get ':project(/:package)/:attribute/edit' => :edit, constraints: cons, as: 'edit'
        get ':project(/:package)' => :index, constraints: cons, as: 'index', defaults: { format: 'html' }
      end
    end

    resources :image_templates, constraints: cons, only: [:index], controller: 'webui/image_templates'

    resources :download_repositories, constraints: cons, only: [:create, :update, :destroy], controller: 'webui/download_on_demand'

    controller 'webui/configuration' do
      get 'configuration' => :index
      patch 'configuration' => :update
    end
    resources :interconnects, only: [:new, :create], controller: 'webui/interconnects'

    controller 'webui/subscriptions' do
      get 'notifications' => :index
      put 'notifications' => :update
    end

    controller 'webui/architectures' do
      patch 'architectures/bulk_update_availability' => :bulk_update_availability, as: :bulk_update_availability
    end

    resources :architectures, only: [:index, :update], controller: 'webui/architectures'

    controller 'webui/monitor' do
      get 'monitor/' => :index
      get 'monitor/old' => :old
      get 'monitor/update_building' => :update_building
      get 'monitor/events' => :events, as: :monitor_events
    end

    resources :package, only: [:index], controller: 'webui/package', constraints: cons

    defaults format: 'html' do
      controller 'webui/package' do
        get 'package/show/:project/:package' => :show, as: 'package_show', constraints: cons
        get 'package/dependency/:project/:package' => :dependency, constraints: cons, as: 'package_dependency'
        get 'package/binary/:project/:package/:repository/:arch/:filename' => :binary, constraints: cons, as: 'package_binary'
        get 'package/binary/download/:project/:package/:repository/:arch/:filename' => :binary_download,
            constraints: cons, as: 'package_binary_download'
        get 'package/binaries/:project/:package/:repository' => :binaries, constraints: cons, as: 'package_binaries'
        get 'package/users/:project/:package' => :users, as: 'package_users', constraints: cons
        get 'package/requests/:project/:package' => :requests, as: 'package_requests', constraints: cons
        get 'package/statistics/:project/:package/:repository/:arch' => :statistics, as: 'package_statistics', constraints: cons
        get 'package/revisions/:project/:package' => :revisions, constraints: cons, as: 'package_view_revisions'
        post 'package/submit_request/:project/:package' => :submit_request, constraints: cons
        get 'package/add_person/:project/:package' => :add_person, constraints: cons, as: 'package_add_person'
        get 'package/add_group/:project/:package' => :add_group, constraints: cons, as: 'package_add_group'
        get 'package/rdiff/:project/:package' => :rdiff, constraints: cons, as: 'package_rdiff'
        post 'package/save_new/:project' => :save_new, constraints: cons, as: 'save_new_package'
        post 'package/branch' => :branch, constraints: cons
        post 'package/save/:project/:package' => :save, constraints: cons, as: 'package_save'
        post 'package/remove/:project/:package' => :remove, constraints: cons
        get 'package/add_file/:project/:package' => :add_file, constraints: cons, as: 'package_add_file'
        post 'package/save_file/:project/:package' => :save_file, constraints: cons
        post 'package/remove_file/:project/:package/:filename' => :remove_file, constraints: cons
        post 'package/save_person/:project/:package' => :save_person, constraints: cons, as: 'package_save_person'
        post 'package/save_group/:project/:package' => :save_group, constraints: cons, as: 'package_save_group'
        post 'package/remove_role/:project/:package' => :remove_role, constraints: cons, as: 'package_remove_role'
        get 'package/view_file/:project/:package/(:filename)' => :view_file, constraints: cons, as: 'package_view_file'
        get 'package/live_build_log/:project/:package/:repository/:arch' => :live_build_log, constraints: cons, as: 'package_live_build_log'
        defaults format: 'js' do
          get 'package/linking_packages/:project/:package' => :linking_packages, constraints: cons, as: 'linking_packages'
          get 'package/update_build_log/:project/:package/:repository/:arch' => :update_build_log, constraints: cons, as: 'package_update_build_log'
          get 'package/submit_request_dialog/:project/:package' => :submit_request_dialog, constraints: cons, as: 'package_submit_request_dialog'
          get 'package/delete_dialog/:project/:package' => :delete_dialog, constraints: cons, as: 'package_delete_dialog'
          post 'package/trigger_rebuild/:project/:package' => :trigger_rebuild, constraints: cons, as: 'package_trigger_rebuild'
          get 'package/abort_build/:project/:package' => :abort_build, constraints: cons, as: 'package_abort_build'
          post 'package/trigger_services/:project/:package' => :trigger_services, constraints: cons, as: 'package_trigger_services'
          delete 'package/wipe_binaries/:project/:package' => :wipe_binaries, constraints: cons, as: 'package_wipe_binaries'
        end
        get 'package/devel_project/:project/:package' => :devel_project, constraints: cons, as: 'package_devel_project'
        get 'package/buildresult' => :buildresult, constraints: cons, as: 'package_buildresult'
        get 'package/rpmlint_result' => :rpmlint_result, constraints: cons, as: 'rpmlint_result'
        get 'package/rpmlint_log' => :rpmlint_log, constraints: cons
        get 'package/meta/:project/:package' => :meta, constraints: cons, as: 'package_meta'
        post 'package/save_meta/:project/:package' => :save_meta, constraints: cons, as: 'package_save_meta'
        # For backward compatibility
        get 'package/attributes/:project/:package', to: redirect('/attribs/%{project}/%{package}'), constraints: cons
        get 'package/edit/:project/:package' => :edit, constraints: cons, as: :package_edit
        # For backward compatibility
        get 'package/repositories/:project/:package', to: redirect('/repositories/%{project}/%{package}'), constraints: cons
        get 'package/import_spec/:project/:package' => :import_spec, constraints: cons
        # For backward compatibility
        get 'package/files/:project/:package' => :show, constraints: cons
      end
    end

    resources :packages, only: [], param: :name do
      resource :job_history, controller: 'webui/packages/job_history', only: [] do
        get '/:project/:repository/:arch' => :index, as: :index, constraints: cons
      end

      resource :build_reason, controller: 'webui/packages/build_reason', only: [] do
        get '/:project/:repository/:arch' => :index, as: :index, constraints: cons
      end
    end

    controller 'webui/patchinfo' do
      post 'patchinfo' => :create
      get 'patchinfo/edit' => :edit, as: 'edit_patchinfo'
      put 'patchinfo/:project/:package' => :update, constraints: cons, as: 'update_patchinfo'
      delete 'patchinfo' => :destroy
      post 'patchinfo/update_issues/:project/:package' => :update_issues, as: 'update_issues_patchinfo'
      get 'patchinfo/show/:project/:package' => :show, as: 'patchinfo_show', constraints: cons, defaults: { format: 'html' }
      get 'patchinfo/new_tracker' => :new_tracker
      get 'patchinfo/delete_dialog' => :delete_dialog
    end

    controller 'webui/repositories' do
      get 'repositories/:project(/:package)' => :index, constraints: cons, as: 'repositories', defaults: { format: 'html' }
      get 'project/repositories/:project' => :index, constraints: cons, as: 'project_repositories'
      get 'project/add_repository/:project' => :new, constraints: cons

src/api/app/controllers/webui/announcements_controller.rb
class Webui::AnnouncementsController < Webui::WebuiController
  def show
    @hide_announcement_notification = true
    @announcement = Announcement.find_by(id: params[:id])

    redirect_back(fallback_location: root_path, error: "Couldn't find announcement") unless @announcement
    switch_to_webui2
  end
end

src/api/app/controllers/webui/apidocs_controller.rb
class Webui::ApidocsController < Webui::WebuiController
  def index
    filename = File.expand_path(CONFIG['apidocs_location']) + '/index.html'
    if File.exist?(filename)
      render file: filename, formats: [:html]
    else
      logger.error "Unable to load apidocs index file from #{CONFIG['apidocs_location']}. Did you create the apidocs?"
      flash[:error] = 'Unable to load API documentation.'
      redirect_back(fallback_location: root_path)
    end
  end

  def file
    # Ensure it really is just a file name, no '/..', etc.
    filename = File.basename(params[:filename])
    file = File.expand_path(File.join(CONFIG['schema_location'], filename))
    if File.exist?(file)
      send_file(file, type: 'text/xml', disposition: 'inline')
    else
      flash[:error] = "File not found: #{params[:filename]}"
      redirect_back(fallback_location: { controller: 'apidocs', action: 'index' })
    end
    return
  end
end

src/api/app/controllers/webui/architectures_controller.rb
# Enabling/Disabling default architectures
class Webui::ArchitecturesController < Webui::WebuiController
  before_action :require_admin

  def index
    @architectures = Architecture.order(:name)

    # TODO: Remove the statement after migration is finished
    switch_to_webui2
  end

  def update
    architecture = Architecture.find(params[:id])

    if architecture.update(available: params[:available] == 'true')
      flash.now[:success] = "Updated architecture '#{architecture.name}'"
      ::Configuration.write_to_backend
      status = :ok
    else
      flash.now[:error] = "Updating architecture '#{architecture.name}' failed: " \
        "#{architecture.errors.full_messages.to_sentence}"
      status = :unprocessable_entity
    end

    respond_to do |format|
      format.js { render 'webui2/webui/architectures/update', status: status }
    end
  end

  def bulk_update_availability
    result = ::ArchitecturesControllerService::ArchitectureUpdater.new(params).call

    respond_to do |format|
      if result.valid?
        ::Configuration.write_to_backend
        format.js do
          flash.now[:success] = 'Updated availability for all architectures.'
          render 'webui2/webui/architectures/bulk_update_availability'
        end
        format.html { redirect_to architectures_path, success: 'Architectures successfully updated.' }
      else
        format.js do
          flash.now[:error] = 'Updating architecture availability failed.'
          render 'webui2/webui/architectures/bulk_update_availability', status: :unprocessable_entity
        end
        format.html { redirect_back(fallback_location: root_path, error: 'Not all architectures could be saved') }
      end
    end
  end
end

src/api/app/controllers/webui/attribute_controller.rb
class Webui::AttributeController < Webui::WebuiController
  include Webui2::AttributeController

  helper :all
  before_action :set_container, only: [:index, :new, :edit]
  before_action :set_attribute, only: [:update, :destroy]

  # raise an exception if authorize has not yet been called.
  after_action :verify_authorized, except: :index

  helper 'webui/project'

  def index
    @attributes = @container.attribs.includes(:issues, :values, attrib_type: [:attrib_namespace]).sort_by(&:fullname)

    switch_to_webui2
  end

  def new
    if @package
      @attribute = Attrib.new(package_id: @package.id)
    else
      @attribute = Attrib.new(project_id: @project.id)
    end

    authorize @attribute, :create?

    switch_to_webui2
  end

  def edit
    @attribute = Attrib.find_by_container_and_fullname(@container, params[:attribute])
    raise ActiveRecord::RecordNotFound unless @attribute

    authorize @attribute

    value_count = @attribute.attrib_type.value_count
    values_length = @attribute.values.length
    if value_count && (value_count > values_length)
      (value_count - values_length).times { @attribute.values.build(attrib: @attribute) }
    end

    switch_to_webui2
  end

  def create
    @attribute = Attrib.new(attrib_params)

    authorize @attribute

    # build the default values
    if @attribute.attrib_type.value_count
      @attribute.attrib_type.value_count.times do
        @attribute.values.build(attrib: @attribute)
      end
    end

    if @attribute.save
      if @attribute.values_editable?
        redirect_to edit_attribs_path(project: @attribute.project.to_s, package: @attribute.package.to_s,
                                      attribute: @attribute.fullname),
                    success: 'Attribute was successfully created.'
      else
        redirect_to index_attribs_path(project: @attribute.project.to_s, package: @attribute.package.to_s),
                    success: 'Attribute was successfully created.'
      end
    else
      redirect_back(fallback_location: root_path, error: "Saving attribute failed: #{@attribute.errors.full_messages.join(', ')}")
    end
  end

  def update
    authorize @attribute

    if @attribute.update(attrib_params)
      @attribute.write_container_attributes
      redirect_to edit_attribs_path(project: @attribute.project.to_s, package: @attribute.package.to_s, attribute: @attribute.fullname),
                  success: 'Attribute was successfully updated.'
    else
      redirect_back(fallback_location: root_path, error: "Updating attribute failed: #{@attribute.errors.full_messages.join(', ')}")
    end
  end

  def destroy
    authorize @attribute

    @attribute.destroy
    redirect_back(fallback_location: root_path, success: 'Attribute sucessfully deleted!')
  end

  private

  def set_container
    begin
      @project = Project.get_by_name(params[:project])
    rescue APIError
      flash[:error] = "Project not found: #{params[:project]}"
      redirect_to(controller: 'project') && return
    end
    if params[:package]
      begin
        @package = Package.get_by_project_and_name(params[:project], params[:package], use_source: false)
      rescue APIError
        redirect_to(project_show_path(@project.to_s), error: "Package #{params[:package]} not found") && (return)
      end
      @container = @package
    else
      @container = @project
    end
  end

  def set_attribute
    @attribute = Attrib.find(params[:id])
    if @attribute.container.instance_of?(Package)
      @package = @attribute.container
      @project = @package.project
    elsif @attribute.container.instance_of?(Project)
      @project = @attribute.container
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def attrib_params
    params.require(:attrib).permit(:attrib_type_id, :project_id, :package_id,
                                   values_attributes: [:id, :value, :position, :_destroy],
                                   issues_attributes: [:id, :name, :issue_tracker_id, :_destroy])
  end
end

src/api/app/controllers/webui/cloud/configurations_controller.rb
module Webui
  module Cloud
    class ConfigurationsController < WebuiController
      before_action :set_breadcrumb

      def index
        switch_to_webui2
        @crumb_list.push << 'Configuration'
      end

      private

      def set_breadcrumb
        @crumb_list = [WebuiController.helpers.link_to('Cloud Upload', cloud_upload_index_path)]
      end
    end
  end
end

src/api/app/views/webui2/webui/patchinfo/_breadcrumb_items.html.haml
= render partial: 'webui/main/breadcrumb_items'
%li.breadcrumb-item
  = link_to('Projects', projects_path)
%li.breadcrumb-item
  = link_to(@project, project_show_path(@project))
%li.breadcrumb-item.active{ 'aria-current' => 'page' }
  - case action_name
  - when 'show'
    Details
  - when 'edit'
    Edit Patchinfo

src/api/app/views/webui2/webui/patchinfo/_delete_patchinfo_modal.html.haml
.modal.fade#delete-patchinfo-modal{ tabindex: -1, role: 'dialog', aria: { labelledby: 'delete-patchinfo-modal-label', hidden: true } }
  .modal-dialog.modal-dialog-centered{ role: 'document' }
    .modal-content
      = form_tag(patchinfo_path(project: project, package: package), method: :delete) do
        .modal-header
          %h5.modal-title#delete-patchinfo-modal-label
            Delete Confirmation
        .modal-body
          Do you really want to delete
          = link_to project.name, project_show_path(project)
          \/
          =  link_to package.name, package_show_path(project, package)
          ?
        .modal-footer
          %a.btn.btn-sm.btn-outline-secondary.px-4{ data: { dismiss: 'modal' } }
            Cancel
          = submit_tag('Delete', class: 'btn btn-sm btn-danger px-4')

src/api/app/views/webui2/webui/patchinfo/_side_elements.html.haml
%ul.list-unstyled
  - if patchinfo.block
    %li
      .blocked-release
        %i.fas.fa-info-circle.text-info
        .block-reason
          %span Release is blocked
          - if patchinfo.block_reason.present?
            %small.d-block.mb-1.text-muted= patchinfo.block_reason

  - if packager
    %li
      %i.fas.fa-info-circle.text-info
      %span Submitted by
      %span= user_with_realname_and_icon(packager)
  - if patchinfo.version
    %li
      %i.fas.fa-info-circle.text-info
      %span Version #{patchinfo.version}
  - if patchinfo.relogin_needed
    %li
      %i.fas.fa-exclamation-triangle.text-warning
      %span Relogin is suggested
  - if patchinfo.reboot_needed
    %li
      %i.fas.fa-exclamation-triangle.text-warning
      %span Reboot is suggested
  - if patchinfo.zypp_restart_needed
    %li
      %i.fas.fa-exclamation-triangle.text-warning
      %span Restart package-manager is suggested

src/api/app/views/webui2/webui/patchinfo/edit.html.haml
- @pagetitle = "Edit Patchinfo for #{@project}"

.card
  = render partial: 'webui/package/tabs', locals: { project: @project, package: @package }
  .card-body
    %h3= @pagetitle

    = form_for(@patchinfo, url: update_patchinfo_path(project: @project, package: @package), method: :put, html: { id: 'patchinfo' }) do |form|
      = form.hidden_field(:name)
      .form-group.col-8.col-md-4
        = render partial: 'webui/autocomplete', locals: { html_id: 'patchinfo[packager]', label: 'Packager', value: @patchinfo.packager,
                                                          data: { source: autocomplete_users_path } }
      .form-group.col-md-6
        = form.label(:summary)
        %abbr.text-danger{ title: 'required (minimum 10 characters)' } *
        = form.text_area(:summary, required: true, class: 'form-control', minlength: 10)
        %small.form-text.text-muted Summarize the changes
      .form-group.col-md-6
        = form.label(:description)
        %abbr.text-danger{ title: 'required (minimum 50 characters)' } *
        = form.text_area(:description, required: true, rows: 8, class: 'form-control', minlength: 50)
        %small.form-text.text-muted Fully describe the changes
      .form-group.col-4.col-md-2
        = form.label(:version)
        = form.text_field(:version, class: 'form-control')
      .form-group.col-md-6
        = form.label(:message)
        = form.text_area(:message, rows: 4, class: 'form-control')
      .form-group.col-6.col-md-3
        = form.label(:category)
        = form.select(:category, options_for_select(Patchinfo::CATEGORIES, @patchinfo.category), {}, class: 'custom-select')
      .form-group.col-6.col-md-3
        = form.label(:rating)
        = form.select(:rating, options_for_select(Patchinfo::RATINGS, @patchinfo.rating), {}, class: 'custom-select')
      = render partial: 'webui2/webui/patchinfo/form/issues',
        locals: { form: form, issues: @patchinfo.issues, project: @project, package: @package }
      = render partial: 'webui2/webui/patchinfo/form/required_actions',
        locals: { form: form, zypp_restart_needed: @zypp_restart_needed, relogin: @relogin, reboot: @reboot }
      = render partial: 'webui2/webui/patchinfo/form/binaries',
        locals: { form: form, binarylist: @binarylist, binaries: @patchinfo.binaries }
      = render partial: 'webui2/webui/patchinfo/form/block_release',
        locals: { form: form, patchinfo_block: @patchinfo.block }

      = form.submit('Save', class: 'btn btn-primary', data: { disable_with: 'Saving...' })

- content_for :ready_function do
  setupPatchinfo();

src/api/app/views/webui2/webui/patchinfo/show.html.haml
- @pagetitle = @package

.card.mb-3
  = render partial: 'webui2/webui/package/tabs', locals: { project: @project, package: @package }
  .card-body
    .patchinfo.row
      .col-md-8
        = patchinfo_header(@patchinfo, @pkg_names)
        .mt-3#description-text
          = render partial: 'webui/webui/collapsible_text', locals: { text: @patchinfo.description }
      .col-md-4
        = render partial: 'side_elements', locals: { patchinfo: @patchinfo, packager: @packager }

      .col-md-12
        - if User.possibly_nobody.can_modify?(@package)
          %ul.list-inline.mb-0
            %li.list-inline-item
              = link_to(edit_patchinfo_path(project: @project, package: @package)) do
                %i.fas.fa-edit.text-secondary
                Edit patchinfo
            %li.list-inline-item
              = link_to('#', class: 'nav-link', data: { toggle: 'modal', target: '#delete-patchinfo-modal' }) do
                %i.fas.fa-times-circle.text-danger
                Delete patchinfo
          = render partial: 'delete_patchinfo_modal', locals: { project: @project, package: @package }

.patchinfo.row
  - if @patchinfo.message.present?
    .col-md-12
      .card.mb-3
        %h5.card-header Message
        .card-body
          = simple_format @patchinfo.message

  .col-md-6
    .card.mb-3
      %h5.card-header Fixed bugs
      .card-body
        - @patchinfo.issues.each do |issue|
          .media
            %i.pt-1.mr-1.fas.fa-bug.text-danger
            .media-body.mb-3
              = patchinfo_issue_link(issue[1], issue[0], issue[2])
              - if issue[3].present?
                %small.d-block.text-muted= issue[3]
  .col-md-6
    .card.mb-3
      %h5.card-header Selected Binaries
      .card-body.binaries
        - @patchinfo.binaries.each do |binary|
          %span.badge.badge-warning
            %i.mr-1.fa.fa-archive
            = binary