src/api/config/routes.rb
class WebuiMatcher
  class InvalidRequestFormat < APIError
  end

  def self.matches?(request)
    request.format.to_sym != :xml
  rescue ArgumentError => e
    raise InvalidRequestFormat, e.to_s
  end
end

# here we take everything that is XML, JSON or osc ;)
class APIMatcher
  def self.matches?(request)
    format = request.format.to_sym || :xml
    format == :xml || format == :json || public_or_about_path?(request)
  end

  def self.public_or_about_path?(request)
    request.fullpath.start_with?('/public', '/about')
  end
end

OBSApi::Application.routes.draw do
  mount Peek::Railtie => '/peek'

  cons = {
    arch: %r{[^\/]*},
    binary: %r{[^\/]*},
    filename: %r{[^\/]*},
    id: %r{\d*},
    login: %r{[^\/]*},
    package: %r{[^\/]*},
    package_name: %r{[^\/]*},
    project: %r{[^\/]*},
    project_name: %r{[^\/]*},
    maintained_project: %r{[^\/]*},
    repository: %r{[^\/]*},
    repository_name: %r{[^\/]*},
    service: %r{\w[^\/]*},
    title: %r{[^\/]*},
    user: %r{[^\/]*},
    user_login: %r{[^\/]*},
    repository_publish_build_id: %r{[^\/]*}
  }

  constraints(WebuiMatcher) do
    root 'webui/main#index'

    controller 'webui/main' do
      get 'main/systemstatus' => :systemstatus
    end

    resources :status_messages, only: [:create, :destroy], controller: 'webui/status_messages' do
      collection do
        get 'create_status_message_dialog' => :create_status_message_dialog
        get 'destroy_status_message_dialog' => :destroy_status_message_dialog
      end
    end

    controller 'webui/feeds' do
      get 'main/news' => :news, constraints: ->(req) { req.format == :rss }, as: :news_feed
      get 'main/latest_updates' => :latest_updates, constraints: ->(req) { req.format == :rss }, as: :latest_updates_feed
      get 'project/latest_commits/:project' => :commits, defaults: { format: 'atom' }, constraints: cons, as: 'commits_feed'
      get 'user/feed/:token' => :notifications, defaults: { format: 'rss' }, as: :user_rss_notifications
    end

    resources :attribs, constraints: cons, only: [:create, :update, :destroy], controller: 'webui/attribute' do
      collection do
        get ':project(/:package)/new' => :new, constraints: cons, as: 'new'
        get ':project(/:package)/:attribute/edit' => :edit, constraints: cons, as: 'edit'
        get ':project(/:package)' => :index, constraints: cons, as: 'index', defaults: { format: 'html' }
      end
    end

    resources :image_templates, constraints: cons, only: [:index], controller: 'webui/image_templates'

    resources :download_repositories, constraints: cons, only: [:create, :update, :destroy], controller: 'webui/download_on_demand'

    controller 'webui/configuration' do
      get 'configuration' => :index
      patch 'configuration' => :update
    end
    resources :interconnects, only: [:new, :create], controller: 'webui/interconnects'

    controller 'webui/subscriptions' do
      get 'notifications' => :index
      put 'notifications' => :update
    end

    controller 'webui/architectures' do
      patch 'architectures/bulk_update_availability' => :bulk_update_availability, as: :bulk_update_availability
    end

    resources :architectures, only: [:index, :update], controller: 'webui/architectures'

    controller 'webui/monitor' do
      get 'monitor/' => :index
      get 'monitor/old' => :old
      get 'monitor/update_building' => :update_building
      get 'monitor/events' => :events, as: :monitor_events
    end

    resources :package, only: [:index], controller: 'webui/package', constraints: cons

    defaults format: 'html' do
      controller 'webui/package' do
        get 'package/show/:project/:package' => :show, as: 'package_show', constraints: cons
        get 'package/dependency/:project/:package' => :dependency, constraints: cons, as: 'package_dependency'
        get 'package/binary/:project/:package/:repository/:arch/:filename' => :binary, constraints: cons, as: 'package_binary'
        get 'package/binary/download/:project/:package/:repository/:arch/:filename' => :binary_download,
            constraints: cons, as: 'package_binary_download'
        get 'package/binaries/:project/:package/:repository' => :binaries, constraints: cons, as: 'package_binaries'
        get 'package/users/:project/:package' => :users, as: 'package_users', constraints: cons
        get 'package/requests/:project/:package' => :requests, as: 'package_requests', constraints: cons
        get 'package/statistics/:project/:package/:repository/:arch' => :statistics, as: 'package_statistics', constraints: cons
        get 'package/revisions/:project/:package' => :revisions, constraints: cons, as: 'package_view_revisions'
        post 'package/submit_request/:project/:package' => :submit_request, constraints: cons
        get 'package/add_person/:project/:package' => :add_person, constraints: cons, as: 'package_add_person'
        get 'package/add_group/:project/:package' => :add_group, constraints: cons, as: 'package_add_group'
        get 'package/rdiff/:project/:package' => :rdiff, constraints: cons, as: 'package_rdiff'
        post 'package/save_new/:project' => :save_new, constraints: cons, as: 'save_new_package'
        post 'package/branch' => :branch, constraints: cons
        post 'package/save/:project/:package' => :save, constraints: cons, as: 'package_save'
        post 'package/remove/:project/:package' => :remove, constraints: cons
        get 'package/add_file/:project/:package' => :add_file, constraints: cons, as: 'package_add_file'
        post 'package/save_file/:project/:package' => :save_file, constraints: cons
        post 'package/remove_file/:project/:package/:filename' => :remove_file, constraints: cons
        post 'package/save_person/:project/:package' => :save_person, constraints: cons, as: 'package_save_person'
        post 'package/save_group/:project/:package' => :save_group, constraints: cons, as: 'package_save_group'
        post 'package/remove_role/:project/:package' => :remove_role, constraints: cons, as: 'package_remove_role'
        get 'package/view_file/:project/:package/(:filename)' => :view_file, constraints: cons, as: 'package_view_file'
        get 'package/live_build_log/:project/:package/:repository/:arch' => :live_build_log, constraints: cons, as: 'package_live_build_log'
        defaults format: 'js' do
          get 'package/linking_packages/:project/:package' => :linking_packages, constraints: cons, as: 'linking_packages'
          get 'package/update_build_log/:project/:package/:repository/:arch' => :update_build_log, constraints: cons, as: 'package_update_build_log'
          get 'package/submit_request_dialog/:project/:package' => :submit_request_dialog, constraints: cons, as: 'package_submit_request_dialog'
          get 'package/delete_dialog/:project/:package' => :delete_dialog, constraints: cons, as: 'package_delete_dialog'
          post 'package/trigger_rebuild/:project/:package' => :trigger_rebuild, constraints: cons, as: 'package_trigger_rebuild'
          get 'package/abort_build/:project/:package' => :abort_build, constraints: cons, as: 'package_abort_build'
          post 'package/trigger_services/:project/:package' => :trigger_services, constraints: cons, as: 'package_trigger_services'
          delete 'package/wipe_binaries/:project/:package' => :wipe_binaries, constraints: cons, as: 'package_wipe_binaries'
        end
        get 'package/devel_project/:project/:package' => :devel_project, constraints: cons, as: 'package_devel_project'
        get 'package/buildresult' => :buildresult, constraints: cons, as: 'package_buildresult'
        get 'package/rpmlint_result' => :rpmlint_result, constraints: cons, as: 'rpmlint_result'
        get 'package/rpmlint_log' => :rpmlint_log, constraints: cons
        get 'package/meta/:project/:package' => :meta, constraints: cons, as: 'package_meta'
        post 'package/save_meta/:project/:package' => :save_meta, constraints: cons, as: 'package_save_meta'
        # For backward compatibility
        get 'package/attributes/:project/:package', to: redirect('/attribs/%{project}/%{package}'), constraints: cons
        get 'package/edit/:project/:package' => :edit, constraints: cons, as: :package_edit
        # For backward compatibility
        get 'package/repositories/:project/:package', to: redirect('/repositories/%{project}/%{package}'), constraints: cons
        get 'package/import_spec/:project/:package' => :import_spec, constraints: cons
        # For backward compatibility
        get 'package/files/:project/:package' => :show, constraints: cons
      end
    end

    resources :packages, only: [], param: :name do
      resource :job_history, controller: 'webui/packages/job_history', only: [] do
        get '/:project/:repository/:arch' => :index, as: :index, constraints: cons
      end

      resource :build_reason, controller: 'webui/packages/build_reason', only: [] do
        get '/:project/:repository/:arch' => :index, as: :index, constraints: cons
      end
    end

    controller 'webui/patchinfo' do
      post 'patchinfo' => :create
      get 'patchinfo/edit' => :edit, as: 'edit_patchinfo'
      put 'patchinfo/:project/:package' => :update, constraints: cons, as: 'update_patchinfo'
      delete 'patchinfo' => :destroy
      post 'patchinfo/update_issues/:project/:package' => :update_issues, as: 'update_issues_patchinfo'
      get 'patchinfo/show/:project/:package' => :show, as: 'patchinfo_show', constraints: cons, defaults: { format: 'html' }
      get 'patchinfo/new_tracker' => :new_tracker
      get 'patchinfo/delete_dialog' => :delete_dialog
    end

    controller 'webui/repositories' do
      get 'repositories/:project(/:package)' => :index, constraints: cons, as: 'repositories', defaults: { format: 'html' }
      get 'project/repositories/:project' => :index, constraints: cons, as: 'project_repositories'
      get 'project/add_repository/:project' => :new, constraints: cons

src/api/app/controllers/webui/projects/bs_requests_controller.rb
module Webui
  module Projects
    class BsRequestsController < WebuiController
      before_action :set_project

      def index
        parsed_params = BsRequest::DataTable::ParamsParserWithStateAndType.new(params).parsed_params
        requests_query = BsRequest::DataTable::FindForProjectQuery.new(@project, parsed_params)
        @requests_data_table = BsRequest::DataTable::Table.new(requests_query, params[:draw])

        respond_to do |format|
          if switch_to_webui2?
            format.json { render 'webui2/shared/bs_requests/index' }
          else
            format.json
          end
        end
        switch_to_webui2
      end
    end
  end
end

src/api/app/controllers/webui/projects/meta_controller.rb
module Webui
  module Projects
    class MetaController < WebuiController
      before_action :set_project
      before_action :validate_meta, only: [:update], if: -> { params[:meta] }
      after_action :verify_authorized, only: [:update]

      def show
        @meta = @project.render_xml
        switch_to_webui2
      end

      def update
        authorize @project, :update?
        updater = ::MetaControllerService::ProjectUpdater.new(project: @project, request_data: @request_data).call

        status = if updater.valid?
                   flash.now[:success] = 'Config successfully saved!'
                   200
                 else
                   flash.now[:error] = updater.errors
                   400
                 end
        switch_to_webui2
        render layout: false, status: status, partial: "layouts/#{ui_namespace}/flash", object: flash
      end

      private

      def validate_meta
        meta_validator = ::MetaControllerService::MetaXMLValidator.new(params)
        meta_validator.call
        if meta_validator.errors?
          flash.now[:error] = meta_validator.errors
          render layout: false, status: 400, partial: "layouts/#{ui_namespace}/flash", object: flash
        else
          @request_data = meta_validator.request_data
        end
      end
    end
  end
end

src/api/app/helpers/webui/project_helper.rb
module Webui::ProjectHelper
  include Webui::WebuiHelper

  protected

  def pulse_period(range)
    end_time = Time.zone.today

    start_time = if range == 'month'
                   end_time.prev_month
                 else
                   end_time.prev_week
                 end

    "#{start_time.strftime("%B, #{start_time.day.ordinalize} %Y")} – #{end_time.strftime("%B, #{end_time.day.ordinalize} %Y")}"
  end

  def show_status_comment(comment, package, firstfail, comments_to_clear)
    status_comment_html = ''.html_safe
    if comment
      # TODO: Port _to_remote helpers to jQuery
      status_comment_html = ERB::Util.h(comment)
      if !firstfail
        if User.possibly_nobody.can_modify?(@project)
          status_comment_html += ' '.html_safe + link_to(image_tag('comment_delete.png', size: '16x16', alt: 'Clear'),
                                                         { action: :clear_failed_comment, project: @project,
                                                           package: package, update: valid_xml_id("comment_#{package}") },
                                                         remote: true)
          comments_to_clear << package
        end
      elsif User.possibly_nobody.can_modify?(@project)
        status_comment_html += ' '.html_safe
        status_comment_html += link_to(image_tag('comment_edit.png', alt: 'Edit'),
                                       { action: 'edit_comment_form', comment: comment,
                                         package: package, project: @project,
                                         update: valid_xml_id("comment_edit_#{package}") },
                                       remote: true)
      end
    elsif firstfail
      if User.possibly_nobody.can_modify?(@project)
        status_comment_html += " <span class='unknown_failure'>Unknown build failure ".html_safe +
                               link_to(image_tag('comment_edit.png', size: '16x16', alt: 'Edit'),
                                       { action: 'edit_comment_form', comment: '', package: package,
                                         project: @project, update: valid_xml_id("comment_edit_#{package}") },
                                       remote: true)
        status_comment_html += '</span>'.html_safe
      else
        status_comment_html += "<span class='unknown_failure'>Unknown build failure</span>".html_safe
      end
    end
    status_comment_html + "<span id='".html_safe + valid_xml_id("comment_edit_#{package}") + "'></span>".html_safe
  end

  def project_bread_crumb(*args)
    @crumb_list = [link_to('Projects', project_list_public_path)]
    return if @spider_bot
    # FIXME: should also work for remote
    if @project && @project.is_a?(Project) && !@project.new_record?
      prj_parents = nil
      if @namespace # corner case where no project object is available
        prj_parents = Project.parent_projects(@namespace)
      else
        # FIXME: Some controller's @project is a Project object whereas other's @project is a String object.
        prj_parents = Project.parent_projects(@project.to_s)
      end
      project_list = []
      prj_parents.each do |name, short_name|
        project_list << link_to(short_name, project_show_path(project: name))
      end
      @crumb_list << project_list unless project_list.empty?
    end
    @crumb_list += args
  end

  def format_seconds(secs)
    secs = Integer(secs)
    if secs < 3600
      format('0:%02d', (secs / 60))
    else
      hours = secs / 3600
      secs -= hours * 3600
      format('%d:%02d', hours, secs / 60)
    end
  end

  def rebuild_time_col(package)
    return '' if package.blank?
    btime = @timings[package][0]
    link_to(h(package), controller: '/webui/package', action: :show, project: @project, package: package) + ' ' + format_seconds(btime)
  end

  # bento_only
  def short_incident_name(incident)
    re = Regexp.new("#{@project.name}\:(.*)")
    match = incident.name.match(re)
    return match[1] if match.length > 1
    match[0]
  end

  def patchinfo_rating_color(rating)
    Patchinfo::RATING_COLORS[rating.to_s] || ''
  end

  def patchinfo_category_color(category)
    Patchinfo::CATEGORY_COLORS[category.to_s] || ''
  end

  def incident_issue_color(patchinfo_issues, package_issues)
    return 'red' if package_issues.zero?
    return 'green' if patchinfo_issues == package_issues
    return 'olive' if patchinfo_issues < package_issues
    return 'red'
  end

  def remove_parent_name(project_name, parent_name)
    project_name.slice(parent_name.length + 1, project_name.length)
  end

  STATE_ICONS = {
    'new' => 'flag_green',
    'review' => 'flag_yellow',
    'declined' => 'flag_red'
  }.freeze

  def map_request_state_to_flag(state)
    STATE_ICONS[state.to_s] || ''
  end

  def escape_list(list)
    # The input list is not html_safe because it's
    # user input which we should never trust!!!
    list.map do |p|
      "['".html_safe +
        escape_javascript(p) +
        "']".html_safe
    end.join(',').html_safe
  end

  def show_package_actions?
    return false if @is_maintenance_project
    return false if @project.defines_remote_instance?
    return true unless @is_incident_project && @packages.present? &&
                       @has_patchinfo && @open_release_requests.empty?
    false
  end

  def can_be_released?(project, packages, open_release_requests, has_patchinfo)
    !project.defines_remote_instance? && project.is_maintenance_incident? && packages.present? && has_patchinfo && open_release_requests.blank?
  end
end

src/api/app/views/webui2/webui/projects/pulse/_breadcrumb_items.html.haml
= render partial: 'webui/project/breadcrumb_items'
%li.breadcrumb-item.active{ 'aria-current' => 'page' }
  Pulse

src/api/app/views/webui2/webui/projects/pulse/_pulse_list.html.haml
.row
  .col
    %p
      During this period
      = render partial: 'pulse_list_commits', locals: { commits: commits, updates: updates }
    %p
      = render partial: 'pulse_list_builds', locals: { builds: builds }
      = render partial: 'pulse_list_new', locals: { new_packages: new_packages, deleted_packages: deleted_packages }
      = render partial: 'pulse_list_changes', locals: { project_changes: project_changes }
    %p
      = render partial: 'pulse_list_branches', locals: { branches: branches }
      = render partial: 'pulse_list_comments', locals: { comments: comments }

  .col
    = render partial: 'pulse_list_requests_box', locals: { project: project,
                                                           requests: requests,
                                                           requests_by_percentage: requests_by_percentage,
                                                           requests_by_state: requests_by_state }

.row
  .col
    - package_changes = commits + new_packages + deleted_packages + updates
    - if package_changes.present?
      %h5#pulse-packages
        = link_to('.collapse-package-changes', aria: { controls: 'collapse-package-changes', expanded: 'true' },
                  'data-toggle' => 'collapse', role: 'button') do
          Package Changes
          %small
            %span.collapser (Hide)
            %span.expander (Show)
      %hr
      .collapse.show.collapse-package-changes
        %ul.list-unstyled
          - package_changes.sort_by(&:datetime).reverse_each do |log_entry|
            %li
              = render partial: 'pulse_list_entry', locals: { log_entry: log_entry, project: project }

    - if project_changes.present?
      %h5#pulse-project
        = link_to('.collapse-project-changes', aria: { controls: 'collapse-project-changes', expanded: 'true' },
                  'data-toggle' => 'collapse', role: 'button') do
          Project Changes
          %small
            %span.collapser (Hide)
            %span.expander (Show)
      %hr
      .collapse.show.collapse-project-changes
        %ul.list-unstyled
          - project_changes.each do |log_entry|
            %li
              = render partial: 'pulse_list_entry', locals: { log_entry: log_entry, project: project }

    - if builds.present?
      %h5#pulse-builds
        = link_to('.collapse-builds', aria: { controls: 'collapse-builds', expanded: 'true' }, 'data-toggle' => 'collapse', role: 'button') do
          Builds
          %small
            (in the last 24 hours)
            %span.collapser (Hide)
            %span.expander (Show)
      %hr
      .collapse.show.collapse-builds
        %ul.list-unstyled
          - builds.each do |log_entry|
            %li
              = render partial: 'pulse_list_entry', locals: { log_entry: log_entry, project: project }

    - collaboration = branches + comments
    - if collaboration.present?
      %h5#pulse-collaboration
        = link_to('.collapse-collaboration', aria: { controls: 'collapse-collaboration', expanded: 'true' },
                  'data-toggle' => 'collapse', role: 'button') do
          Collaboration
          %small
            %span.collapser (Hide)
            %span.expander (Show)
      %hr
      .collapse.show.collapse-collaboration
        %ul.list-unstyled
          - collaboration.sort_by(&:datetime).reverse_each.each do |log_entry|
            %li
              = render partial: 'pulse_list_entry', locals: { log_entry: log_entry, project: project }

    - if requests.present?
      %h5#pulse-requests
        = link_to('.collapse-requests', aria: { controls: 'collapse-requests', expanded: 'true' }, 'data-toggle' => 'collapse', role: 'button') do
          Requests
          %small
            %span.collapser (Hide)
            %span.expander (Show)
      %hr
      .collapse.show.collapse-requests
        = render partial: 'pulse_list_requests', locals: { requests: requests }

src/api/app/views/webui2/webui/projects/pulse/_pulse_list_branches.html.haml
- if branches.any?
  People
  = link_to('#pulse-collaboration') do
    branched
  #{pluralize(branches.count, 'package')}.
- else
  No one branched packages from this project.

src/api/app/views/webui2/webui/projects/pulse/_pulse_list_builds.html.haml
- if builds.any?
  - builds = builds.group(:event_type).count
  There
  -# 'has' does not have an inflection and the String
    version of pluralize does not know about the plural
    option like, that's why this is an if...
    'has'.pluralize(builds.values.sum, plural: 'have')
  = builds.values.sum > 1 ? 'have' : 'has'
  been
  = link_to('#pulse-builds') do
    = builds.values.sum
    builds in the last 24 hours
  of which
  %b.text-danger
    = builds.fetch('build_fail', 0)
    failed
  and
  %b.text-success
    = builds.fetch('build_success', 0)
    succeeded
  \.

src/api/app/views/webui2/webui/projects/pulse/_pulse_list_changes.html.haml
- if project_changes.any?
  And the project setup has been changed
  %b
    #{pluralize(project_changes.count, 'time')}.
- else
  And no one touched the project setup.

src/api/app/views/webui2/webui/projects/pulse/_pulse_list_comments.html.haml
- if comments.any?
  And
  - people = comments.group(:user_name).count
  %b
    = pluralize(people.count, 'person')
  added
  = link_to('#pulse-collaboration') do
    = pluralize(comments.count, 'comment')
  in here.
- else
  And no one commented in here.

src/api/app/views/webui2/webui/projects/pulse/_pulse_list_commits.html.haml
- if commits.any?
  - people = commits.group(:user_name).count
  %b
    = pluralize(people.count, 'person')
  added
  = link_to('#pulse-packages') do
    = pluralize(commits.count, 'commit')
  to packages in this project.
  - if updates.any?
    Out of those commits,
    %b
      = pluralize(updates.count, 'was a', plural: 'were')
      version #{'update'.pluralize(updates.count)}.
  - top_committer = commits.group(:user_name).count.max_by { |_, v| v }
  %span{ title: "with #{pluralize(top_committer.second, 'commit')}" }
    %b
      = top_committer.first
    was the busiest commiter, hooray!
- else
  no one committed anything.

src/api/app/views/webui2/webui/projects/pulse/_pulse_list_entry.html.haml
= log_entry.event_type.camelcase.prepend('Event::').constantize.description
- if log_entry.package_name
  (#{link_to(log_entry.package_name, package_show_path(project.name, log_entry.package_name))})
- if log_entry.user_name
  by #{link_to(log_entry.user_name, user_show_path(log_entry.user_name))}
= fuzzy_time(log_entry.datetime)

src/api/app/views/webui2/webui/projects/pulse/_pulse_list_new.html.haml
There was
- if new_packages.any?
  %b.text-success
    = new_packages.count
    = 'package'.pluralize(new_packages.count)
    created
- else
  no package created
- if deleted_packages.any?
  and
  %b.text-danger
    = deleted_packages.count
    deleted.
- else
  \.

src/api/app/views/webui2/webui/projects/pulse/_pulse_list_requests.html.haml
.row
  - @requests.take(30).each do |request|
    %dt.col-1
      %span{ class: "badge progress-state-#{request.state} text-light" }
        = request.state.to_s
    %dd.col-11
      = link_to(request_show_path(request.number), title: request.description) do
        = request.number
      - if request.request_history_elements.any?
        = request.request_history_elements.last.description.gsub('Request', '')
      - else
        was created
      by
      = link_to(user_show_path(request.creator)) do
        = request.creator
      = fuzzy_time(request.updated_at)

src/api/app/views/webui2/webui/projects/pulse/_pulse_list_requests_box.html.haml
.card
  .card-header
    Requests
  .card-body
    - if requests.any?
      .row
        .col
          .progress
            -# haml-lint:disable InlineStyles
            - requests_by_percentage.each do |state, percentage|
              %div{ title: "#{requests_by_state[state]} #{state} requests",
                    class: "progress-bar progress-state-#{state}",
                    'aria-valuemax': '100', 'aria-valuemin': '0', 'aria-valuenow': percentage,
                    role: 'progressbar', style: "width: #{percentage}%" }
            -# haml-lint:enable InlineStyles
          %p
            = link_to('#pulse-requests') do
              = requests_by_state.values.sum
              active requests
      .row
        - requests_by_state.each_key do |state|
          .col.border.text-center
            %p.fa-3x
              %i{ class: "fa #{request_bootstrap_icon(state)} request-state-#{state}" }
            %p
              = pluralize(requests_by_state[state], 'request')
              %br
              in #{state}
    - else
      = link_to(project_requests_path(project)) do
        There have been no requests send to this project.

src/api/app/views/webui2/webui/projects/pulse/_tabs.html.haml
../../project/_tabs.html.haml

src/api/app/views/webui2/webui/projects/pulse/show.html.haml
- @pagetitle = "Pulse for #{@project}"

.card
  = render(partial: 'tabs', locals: { project: @project })

  .card-body
    .row
      .col-8.mb-3
        %h3#range-header
          = pulse_period(@range)
      .col
        .dropdown.float-right
          %button.btn.btn-secondary.dropdown-toggle#period-dropdown{ 'aria-expanded': 'false',
                                                                     'aria-haspopup': 'true',
                                                                     'data-toggle': 'dropdown',
                                                                     type: 'button' }
            Period: One
            %span#range-text
              = @range.capitalize
          .dropdown-menu{ 'aria-labelledby': 'dropdownMenuButton' }
            %h6.dropdown-header
              Period to display:
            = link_to(project_pulse_path(@project), remote: true, type: :json, class: 'dropdown-item') do
              One Week
            = link_to(project_pulse_path(@project, range: 'month'), remote: true, type: :json, class: 'dropdown-item') do
              One Month
    .row
      .col.spinner
        .row
          .col.text-center
            %i.fas.fa-spinner.fa-spin.fa-3x
      .col.d-none#pulse

:javascript
  $.ajax({
    url: "#{project_pulse_path(@project, range: @range)}",
    type: "get",
    dataType: 'script'
  });

  $(".dropdown-item").click(function() {
    $('#pulse, .col.spinner').toggleClass('d-none');
    // FIXME: No idea why this is needed, maybe remote links are not covered by bootstrap?
    $('#period-dropdown').dropdown('toggle')
  });

src/api/app/views/webui2/webui/projects/pulse/show.js.erb
$('#range-header').html("<%= escape_javascript(pulse_period(@range)) %>");
$('#range-text').html("<%= @range.titleize %>");
$('#pulse, .col.spinner').toggleClass('d-none');
$('#pulse').html("<%= escape_javascript render partial: 'pulse_list', locals: { requests_by_percentage: @requests_by_percentage,
                                                                                requests_by_state: @requests_by_state,
                                                                                project: @project,
                                                                                commits: @commits,
                                                                                new_packages: @new_packages,
                                                                                deleted_packages: @deleted_packages,
                                                                                updates: @updates,
                                                                                project_changes: @project_changes,
                                                                                builds: @builds,
                                                                                branches: @branches,
                                                                                comments: @comments,
                                                                                requests: @requests } %>");